[".config/zen/updater.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/arkenfox/user.js/master/updater.sh"
    executable = true
    refreshPeriod = "168h"
[".config/zen/prefsCleaner.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/arkenfox/user.js/master/prefsCleaner.sh"
    executable = true
    refreshPeriod = "168h"
